2025-06-13 18:18:26,071-__main__-INFO-Starting reproducibility attempt for manuscript:data/raw/example_manuscript.txt
2025-06-13 18:18:26,072-__main__-INFO-Using datasets:data/raw/dataset1.csv
2025-06-13 18:18:26,073-__main__-INFO-Step 1: Parsing mauscript...
2025-06-13 18:18:26,078-__main__-INFO-Step 2: Processing data...
2025-06-13 18:18:26,105-__main__-INFO-Step 3: Generating code...
2025-06-13 18:18:26,109-__main__-INFO-Step 4: Recreating environment...
2025-06-13 18:18:26,113-__main__-ERROR-An error occurred during reproducibility attempt:'DockerManager' object has no attribute 'dockerfile'
Traceback (most recent call last):
  File "C:\Users\dhara\inverse-repro-mvp\main.py", line 75, in main
    env_details=env_manager.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\manager.py", line 25, in create_environment
    env_details=self.manager.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\docker_manager.py", line 17, in create_environment
    docker_build_context=os.path.dirname(self.dockerfile.path)
                                         ^^^^^^^^^^^^^^^
AttributeError: 'DockerManager' object has no attribute 'dockerfile'
2025-06-13 18:18:26,120-__main__-INFO-Step 7: Generating reproducibility reports...
2025-06-13 18:18:26,122-report_generator.generator-INFO-JSON report saved to:output\reports\reproducibility_report_2025-06-13T18-18-26-072900.json
2025-06-13 18:18:26,128-report_generator.generator-INFO-Markdown report saved to:output\reports\reproducibility_report_2025-06-13T18-18-26-072900.md
2025-06-13 18:18:26,128-__main__-INFO-Reproducibility report generated:output\reports\reproducibility_report_2025-06-13T18-18-26-072900.json
2025-06-13 18:18:26,129-__main__-INFO-Reproducibility attempts finished.
