2025-06-13 16:23:01,021-__main__-INFO-Starting reproducibility attempt for manuscript:data/raw/example_manuscript.txt
2025-06-13 16:23:01,022-__main__-INFO-Using datasets:data/raw/dataset1.csv
2025-06-13 16:23:01,022-__main__-INFO-Step 1: Parsing mauscript...
2025-06-13 16:23:01,026-__main__-INFO-Step 2: Processing data...
2025-06-13 16:23:01,037-__main__-INFO-Step 3: Generating code...
2025-06-13 16:23:01,040-__main__-INFO-Step 4: Recreating environment...
2025-06-13 16:23:01,284-__main__-ERROR-An error occurred during reproducibility attempt:maximum recursion depth exceeded
Traceback (most recent call last):
  File "C:\Users\dhara\inverse-repro-mvp\main.py", line 75, in main
    env_details=env_manager.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\manager.py", line 25, in create_environment
    env_details=self.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\manager.py", line 25, in create_environment
    env_details=self.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\manager.py", line 25, in create_environment
    env_details=self.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 983 more times]
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\manager.py", line 24, in create_environment
    logger.info(f'Creating {self.env_type} environment... ')
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1280, in emit
    StreamHandler.emit(self, record)
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 706, in format
    s = self.formatMessage(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 675, in formatMessage
    return self._style.format(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 464, in format
    return self._format(record)
           ^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
2025-06-13 16:23:01,382-__main__-INFO-Step 7: Generating reproducibility reports...
2025-06-13 16:23:01,387-report_generator.generator-INFO-JSON report saved to:output\reports\reproducibility_report_2025-06-13T16-23-01-022145.json
2025-06-13 16:23:01,396-report_generator.generator-INFO-Markdown report saved to:output\reports\reproducibility_report_2025-06-13T16-23-01-022145.md
2025-06-13 16:23:01,397-__main__-INFO-Reproducibility report generated:output\reports\reproducibility_report_2025-06-13T16-23-01-022145.json
2025-06-13 16:23:01,397-__main__-INFO-Reproducibility attempts finished.
