2025-06-13 19:09:20,724-__main__-INFO-Starting reproducibility attempt for manuscript:data/raw/example_manuscript.txt
2025-06-13 19:09:20,725-__main__-INFO-Using datasets:data/raw/dataset1.csv
2025-06-13 19:09:20,725-__main__-INFO-Step 1: Parsing mauscript...
2025-06-13 19:09:20,729-__main__-INFO-Step 2: Processing data...
2025-06-13 19:09:20,730-data_processor.processor-INFO-Loading dataset: data/raw/dataset1.csv
2025-06-13 19:09:20,733-data_processor.processor-INFO-Applying processing instructions for dataset1...
2025-06-13 19:09:20,737-data_processor.processor-INFO-Processed data saved to: output\data\processed\dataset1_processed.csv
2025-06-13 19:09:20,738-__main__-INFO-Step 3: Generating code...
2025-06-13 19:09:20,739-code_generator.generator-INFO-Attempting rule-based code generation...
2025-06-13 19:09:20,739-code_generator.rule_based_generator-INFO-Generated data loading code.
2025-06-13 19:09:20,739-code_generator.rule_based_generator-INFO-Generated analysis code.
2025-06-13 19:09:20,739-code_generator.rule_based_generator-INFO-Generated plotting code.
2025-06-13 19:09:20,741-__main__-INFO-Generated code saved to disk at: output\virtual_environment\reproduced_code.py
2025-06-13 19:09:20,741-__main__-INFO-Step 4: Recreating environment...
2025-06-13 19:09:20,741-environment_generator.manager-INFO-Creating docker environment... 
2025-06-13 19:09:20,744-environment_generator.docker_manager-INFO-Dockerfile generated at: output\virtual_environment\Dockerfile
2025-06-13 19:09:20,746-environment_generator.docker_manager-INFO-requirements.txt generated for Docker at: output\virtual_environment\requirements.txt
2025-06-13 19:09:20,747-environment_generator.docker_manager-INFO-Building Docker image:reproducibility_env...
2025-06-13 19:09:43,770-environment_generator.docker_manager-ERROR-Failed to build Docker image.
2025-06-13 19:09:43,771-environment_generator.docker_manager-ERROR-Command: dockerbuild-treproducibility_env-foutput\virtual_environment\Dockerfileoutput\virtual_environment 
2025-06-13 19:09:43,771-environment_generator.docker_manager-ERROR-Docker STDOUT:

2025-06-13 19:09:43,771-environment_generator.docker_manager-ERROR-Docker STDERR:
None
2025-06-13 19:09:43,771-__main__-ERROR-An error occurred during reproducibility attempt:Command '['docker', 'build', '-t', 'reproducibility_env', '-f', 'output\\virtual_environment\\Dockerfile', 'output\\virtual_environment']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\dhara\inverse-repro-mvp\main.py", line 84, in main
    env_details=env_manager.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\manager.py", line 25, in create_environment
    env_details=self.manager.create_environment()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhara\inverse-repro-mvp\environment_generator\docker_manager.py", line 19, in create_environment
    subprocess.run(
  File "C:\Users\dhara\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'reproducibility_env', '-f', 'output\\virtual_environment\\Dockerfile', 'output\\virtual_environment']' returned non-zero exit status 1.
2025-06-13 19:09:43,777-__main__-INFO-Step 7: Generating reproducibility reports...
2025-06-13 19:09:43,778-report_generator.generator-INFO-JSON report saved to:output\reports\reproducibility_report_2025-06-13T19-09-20-725028.json
2025-06-13 19:09:43,785-report_generator.generator-INFO-Markdown report saved to:output\reports\reproducibility_report_2025-06-13T19-09-20-725028.md
2025-06-13 19:09:43,786-__main__-INFO-Reproducibility report generated:output\reports\reproducibility_report_2025-06-13T19-09-20-725028.json
2025-06-13 19:09:43,786-__main__-INFO-Reproducibility attempts finished.
